services:
  app:
    image: task_system
    container_name: task_system
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"
    depends_on:
      - db_pg
    environment:
      SPRING_DATASOURCE_URL: 'dbc:postgresql://db_pg:5432/task_management_system'

  db_pg:
    image: postgres
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: task_management_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 13092001
    ports:
      - "5432"